import random
from datetime import datetime, timedelta, timezone


import psycopg2
from faker import Faker


DDL_SQL = """
DROP TABLE IF EXISTS "campaign_clients";
DROP TABLE IF EXISTS "campaigns";
DROP TABLE IF EXISTS "clients";
DROP TABLE IF EXISTS "templates";

CREATE TABLE "campaign_clients" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "campaign_id" int,
  "client_id" int,
  "sent_at" timestamp,
  "status" varchar,
  "opened_at" timestamp,
  "clicked_at" timestamp
);

CREATE TABLE "clients" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" varchar,
  "gender" varchar,
  "email" varchar UNIQUE,
  "segment" varchar,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "campaigns" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "template_id" int,
  "description" text,
  "status" varchar,
  "created_at" timestamp DEFAULT (now()),
  "planned_at" timestamp
);

CREATE TABLE "templates" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" varchar,
  "name" varchar,
  "subject" varchar,
  "body_male" text,
  "body_female" text,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now())
);

COMMENT ON COLUMN "clients"."gender" IS 'M / F';
COMMENT ON COLUMN "templates"."type" IS 'WELCOME, WINBACK, DISCOUNT, BIRTHDAY, INFO, ...';
COMMENT ON COLUMN "campaigns"."status" IS 'DRAFT, SCHEDULED, RUNNING, FINISHED, CANCELLED';
COMMENT ON COLUMN "campaign_clients"."status" IS 'PLANNED, SENT, OPENED, CLICKED, BOUNCED';

ALTER TABLE "campaign_clients" ADD FOREIGN KEY ("campaign_id") REFERENCES "campaigns" ("id");
ALTER TABLE "campaign_clients" ADD FOREIGN KEY ("client_id") REFERENCES "clients" ("id");
ALTER TABLE "campaigns" ADD FOREIGN KEY ("template_id") REFERENCES "templates" ("id");
"""


def init_db():
    # ⚠️ Подставь свои параметры подключения
    conn = psycopg2.connect(
        dbname="postgres",
        user="postgres",
        password="12345",
        host="localhost",
        port=5432,
    )

    fake = Faker("ru_RU")
    random.seed(42)
    Faker.seed(42)

    try:
        with conn:
            with conn.cursor() as cur:
                # Создаём схему
                cur.execute(DDL_SQL)
                print("Схема БД пересоздана.")

                # ---------- TEMPLATES ----------
                templates_data = [
                    (
                        "WELCOME",
                        "Приветственное письмо",
                        "Добро пожаловать в наш сервис",
                        "Здравствуйте, {name}! Рады видеть вас среди наших клиентов (M).",
                        "Здравствуйте, {name}! Рады видеть вас среди наших клиенток (F).",
                    ),
                    (
                        "DISCOUNT",
                        "Персональная скидка 10%",
                        "Ваша персональная скидка 10%",
                        "{name}, для вас действует скидка 10% на следующий заказ (M).",
                        "{name}, для вас действует скидка 10% на следующий заказ (F).",
                    ),
                    (
                        "WINBACK",
                        "Мы по вам скучаем",
                        "Давно не заходили — вот бонус",
                        "{name}, мы давно вас не видели. Возвращайтесь и получите бонус (M).",
                        "{name}, мы давно вас не видели. Возвращайтесь и получите бонус (F).",
                    ),
                    (
                        "BIRTHDAY",
                        "Поздравление с днём рождения",
                        "С днём рождения!",
                        "{name}, поздравляем с днём рождения и дарим вам подарок (M).",
                        "{name}, поздравляем с днём рождения и дарим вам подарок (F).",
                    ),
                    (
                        "INFO",
                        "Обновления сервиса",
                        "Что нового в сервисе",
                        "{name}, рассказываем о новых возможностях нашего сервиса (M).",
                        "{name}, рассказываем о новых возможностях нашего сервиса (F).",
                    ),
                ]

                cur.executemany(
                    """
                    INSERT INTO templates (type, name, subject, body_male, body_female)
                    VALUES (%s, %s, %s, %s, %s)
                    """,
                    templates_data,
                )
                print("Добавлено шаблонов:", len(templates_data))

                # Получаем id шаблонов
                cur.execute('SELECT id, type FROM templates ORDER BY id')
                templates = cur.fetchall()  # [(id, type), ...]

                # ---------- CLIENTS ----------
                segments = ["new", "active", "churn_risk", "vip"]
                clients_to_insert = []

                for _ in range(50):
                    gender = random.choice(["M", "F"])
                    full_name = (
                        fake.name_male() if gender == "M" else fake.name_female()
                    )
                    email = fake.unique.email()
                    segment = random.choice(segments)
                    clients_to_insert.append((full_name, gender, email, segment))

                cur.executemany(
                    """
                    INSERT INTO clients (full_name, gender, email, segment)
                    VALUES (%s, %s, %s, %s)
                    """,
                    clients_to_insert,
                )
                print("Добавлено клиентов:", len(clients_to_insert))

                # Получаем id клиентов
                cur.execute("SELECT id FROM clients ORDER BY id")
                client_ids = [row[0] for row in cur.fetchall()]

                # ---------- CAMPAIGNS ----------
                now = datetime.now(timezone.utc)

                campaigns_data = [
                    (
                        "Приветственная кампания",
                        templates[0][0],  # id первого шаблона (WELCOME)
                        "Приветственное письмо новым клиентам.",
                        "FINISHED",
                        now - timedelta(days=10),
                    ),
                    (
                        "Весенняя скидка 10%",
                        templates[1][0],  # DISCOUNT
                        "Скидка 10% для активных клиентов.",
                        "RUNNING",
                        now - timedelta(days=3),
                    ),
                    (
                        "Реактивация уснувших клиентов",
                        templates[2][0],  # WINBACK
                        "Возвращаем клиентов, которые давно не заходили.",
                        "SCHEDULED",
                        now + timedelta(days=2),
                    ),
                ]

                # templates[x][0] — id, потому что в выборке (id, type)

                campaigns_to_insert = [
                    (name, template_id, desc, status, planned_at)
                    for (name, template_id, desc, status, planned_at) in campaigns_data
                ]

                cur.executemany(
                    """
                    INSERT INTO campaigns (name, template_id, description, status, planned_at)
                    VALUES (%s, %s, %s, %s, %s)
                    """,
                    campaigns_to_insert,
                )
                print("Добавлено кампаний:", len(campaigns_to_insert))

                # Получаем id и planned_at для кампаний
                cur.execute(
                    "SELECT id, planned_at FROM campaigns ORDER BY id"
                )
                campaigns = cur.fetchall()  # [(id, planned_at), ...]

                # ---------- CAMPAIGN_CLIENTS ----------
                campaign_clients_rows = []

                for campaign_id, planned_at in campaigns:
                    # Кол-во получателей в кампании
                    num_recipients = random.randint(15, 30)
                    recipients = random.sample(client_ids, num_recipients)

                    base_time = planned_at or now

                    for client_id in recipients:
                        sent_at = base_time + timedelta(
                            minutes=random.randint(-60, 0)
                        )

                        r = random.random()
                        # 0.0–0.2 → CLICKED (20%)
                        # 0.2–0.8 → OPENED (60%)
                        # 0.8–0.95 → SENT (15%)
                        # 0.95–1.0 → BOUNCED (5%)
                        if r < 0.2:
                            status = "CLICKED"
                            opened_at = sent_at + timedelta(
                                minutes=random.randint(1, 30)
                            )
                            clicked_at = opened_at + timedelta(
                                minutes=random.randint(1, 15)
                            )
                        elif r < 0.8:
                            status = "OPENED"
                            opened_at = sent_at + timedelta(
                                minutes=random.randint(1, 60)
                            )
                            clicked_at = None
                        elif r < 0.95:
                            status = "SENT"
                            opened_at = None
                            clicked_at = None
                        else:
                            status = "BOUNCED"
                            opened_at = None
                            clicked_at = None

                        campaign_clients_rows.append(
                            (
                                campaign_id,
                                client_id,
                                sent_at,
                                status,
                                opened_at,
                                clicked_at,
                            )
                        )

                cur.executemany(
                    """
                    INSERT INTO campaign_clients
                        (campaign_id, client_id, sent_at, status, opened_at, clicked_at)
                    VALUES (%s, %s, %s, %s, %s, %s)
                    """,
                    campaign_clients_rows,
                )
                print("Добавлено отправок (campaign_clients):", len(campaign_clients_rows))

        print("Инициализация и заполнение БД завершены успешно.")
    finally:
        conn.close()


if __name__ == "__main__":
    init_db()
